# Site settings
name: 黑色星期天
email: liutao_l@126.com
author: LT
url: 
resume_site: 
github: https://github.com/liutao0623/
baseurl: ""
description: good good study,day day up
meta_description: 刘韬;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liutao0623

# Build settings
markdown: kramdown

baidu_analysis: 
